service: serverless-API-FRG

plugins:
  - serverless-python-requirements
  - serverless-wsgi
custom:
  wsgi:
    app: app.app
    packRequirements: false

provider:
  name: aws
  runtime: python3.7
  region: eu-west-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource: "arn:aws:s3:::boto3-etienne/*"

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http:
          path: json
          method: POST
